[alias]
full = "run --release --features backtracker-full"
fullmt = "run --release --features backtracker-full,mt"
mids = "run --release --features backtracker-mids"
midsmt = "run --release --features backtracker-mids,mt"
ddfull = "run --features backtracker-full"
ddmids = "run --features backtracker-mids"
