[alias]
full = "run --release --features backtracker-full"
mids = "run --release --features backtracker-mids"
fullmt = "full --features mt"
midsmt = "mids --features mt"
ddfull = "run --features backtracker-full"
ddmids = "run --features backtracker-mids"
